name: 'Assign Users on Issue Open'
on:
  issues:
    types: [opened]

jobs:
  assign_users:
    runs-on: ubuntu-latest
    steps:
      - name: Assign users
        uses: actions/add-to-project@v0.1.0
        with:
          assignees: 'user1,user2'  # Replace with the GitHub usernames of the users to assign
